version: "3"

services:
  django:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/home/kanny/staticfiles
    ports:
        - 8000:8000
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kanny
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=publisher
    ports:
      - 5432:5447
volumes:
  postgres_data:
  static_volume:
  media:
