# Generated by Django 3.1.2 on 2020-10-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications_table', '0002_auto_20201023_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='publications_table.Author', verbose_name='авторы'),
        ),
    ]
