version: "3"

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/home/kanny/staticfiles
    ports:
        - 8000:8000
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kanny
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=publisher
volumes:
  postgres_data:
  static_volume:
  media:
